CREATE SEQUENCE test_objects_id_pk_seq;

create TABLE IF NOT EXISTS TEST_OBJECTS (
    ID SERIAL NOT NULL,
	HASH VARCHAR(15) UNIQUE,
	COLUMN_1 VARCHAR(15),
	COLUMN_2 VARCHAR(15),
	created DATE,
	updated TIME,
	PRIMARY KEY (ID)
);
